# Generated by Django 5.2.16 on 2026-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
    ]
