# Generated by Django 5.2.16 on 2026-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
    ]
