# Generated by Django 5.2.16 on 2026-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_emp_heroes_members_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.EmailField(max_length=6)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
