# Generated by Django 5.2.16 on 2026-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
        migrations.DeleteModel(
            name='heroes',
        ),
        migrations.DeleteModel(
            name='members',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=6),
        ),
    ]
