# Generated by Django 5.2.16 on 2026-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_emp_delete_heroes_delete_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='Pune', max_length=50),
        ),
    ]
